version: '3.3'

networks:
  replicated-network:
    external: false

services:

  replicated-log-master:
    hostname: replicated-log-master
    image: replicated-log-master
    networks:
      - replicated-network
    container_name: replicated-log-master-container
    build:
      context: replicated-log-master
      dockerfile: replicated-log-master/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ALL_SECONDARY_URL=http://replicated-log-secondary-1:8081/secondary;http://replicated-log-secondary-2:8082/secondary;
    restart: always


  replicated-log-secondary-1:
    hostname: replicated-log-secondary-1
    image: replicated-log-secondary-1
    networks:
      - replicated-network
    container_name: replicated-log-secondary-1-container
    build:
      context: replicated-log-secondary
      dockerfile: replicated-log-secondary/DockerfileSecondary1
    ports:
      - "8081:8081"
    restart: always


  replicated-log-secondary-2:
    hostname: replicated-log-secondary-2
    image: replicated-log-secondary-2
    networks:
      - replicated-network
    container_name: replicated-log-secondary-2-container
    build:
      context: replicated-log-secondary
      dockerfile: replicated-log-secondary/DockerfileSecondary2
    ports:
      - "8082:8081"
    restart: always


